### ISSUE TITLE
Missing Exchange Admin permissions for Katie Jordan

### ISSUE THREAD

**Issue by mct370770** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#101]
# Module: 02
##### Step: 03-04

Description of issue
Katie Jordan is not made an Exchange Online Administrator
And therefore cannot execute the powershell "New-Mailbox"
Repro steps:

1. Katie Jordan is not made an Exchange Online Administrator
And therefore cannot execute the powershell "New-Mailbox"

**Comment by Yiizo** [comment]
I can confirm this has also been replicated.

**Comment by dahans-msft2** [comment]
This is resovled with PR #102 by giving Katie Jordan Exchange Admin permissions.
