### ISSUE TITLE
Toll Number not available in the list

### ISSUE THREAD

**Issue by mctniteshshukla** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#14]
# Module: 02
#### Step: 07

Description of issue - in this step "Select the Toll number dropdown and change it to +1 689 206 9333 Orlando, United States" toll number is not available in the list.

Repro steps: Searched multiple times.

1. Searched multiple times.
1. Searched multiple times.
1. Searched multiple times.

**Comment by dahans-msft2** [comment]
@mctniteshshukla - The number may not always be available or be the same in your region.  I would try to move forward with a different number if possible.  I've added a note to this effect for the next update of the instructions.  I'll go ahead and close this issue and link it when I merge the next PR.
