### ISSUE TITLE
Lab 3: 'Audiocodes SBC' option no longer present in portal.azure.com 'create a resource' search, unable to proceed.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#18]
# Module: 01 Plan and configure Teams Phone
#### Step: 04

Description of issue

- No results when searching for ‘Audiocodes SBC’, and attempts to use an entry that matches Step 5's 'Mediant VE Session Border Controller (SBC)' fails with settings/defaults that do not appear to match existing instructions.  
- It would seem this value has been changed by Audiocodes company, and is now different since original course release?

Repro steps:

- Lab 3, Exercise 1, Task 5, Step 4, no results:
![image](https://user-images.githubusercontent.com/49700217/148702291-6a5d7d2b-8a38-4514-af26-041c7cfc3640.png)

- If I search directly for ‘Mediant VE Session Border Controller (SBC)’ instead, I do come up with a result:
![image](https://user-images.githubusercontent.com/49700217/148702309-06a374c1-fec6-4b47-817a-c1c412e3ca48.png)

- However, when trying to use this for the rest of Task 5, I end up in Task 7 with no ‘Teams-TLSContext’ entry to upload Trusted Root Cert + other certs, just one called ‘default’:
![image](https://user-images.githubusercontent.com/49700217/148702346-478f81b8-4a5a-4cbd-bb71-7e7499db4934.png)

- Went ahead with instructions, on the assumption that perhaps  ‘default’ is now the equivalent of ‘Teams-TLSContext’.

- Noted that, at least in this resource, the **sbcadmin** account must now be created with a minimum 12-char pwd (just existing Pa55w.rd wont work anymore, needed to choose ‘Pa55w.rd1234’ and adjust that in later instructions referencing this account.

- On several occasions, (initially, and then later when it appeared to auto-redirect me from the IP -> DNS name) I had to click through Edge browsers certificate warning prompts which included both the initial IP address mismatch, and something called ‘NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED’.  Probably good to include some form of ‘note’ describing this process – mainly to tell student to  just ignore the warning & click ‘Continue to <IPAddressOrDNSname>, as some students will likely be confused/blocked by this and call in support tickets requesting how to proceed)

- In Task 9, Step 4, I wasn’t able to proceed much further…I’ve never used this particular app/functionality before, and as the instructions diverged notably from the values I was seeing….I was unable to find the right combination of settings that worked. (and it may have been an improper assumption on my part that the '‘Mediant VE Session Border Controller (SBC)’  was the correct new resource to create.  

- Unfortunately, not sure which one to use, and/or how to proceed with instructions for this Lab.

**Comment by dahans-msft2** [comment]
Acknowledged, investigating...

**Comment by dahans-msft2** [comment]
@TesterTesterson1004 It took a while, but I've resolved all these issues.  I had to make some adjustments, but got it working so users can proceed.
