### ISSUE TITLE
Issue in Task 3 – Configure a Call Queue to use a channel

### ISSUE THREAD

**Issue by ZuberAgwan** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#36]
# Module: Lab 02: Configure your environment for Teams Phone
#### Step: 04

Description of issue
"Contoso loves Teams" This Team does not exist in the lab environment and there is no step mentioned anywhere before this task to create it

**Comment by dahans-msft2** [comment]
Fixed in PR #49
