### ISSUE TITLE
Azure Pass redemption doesn't complete / Azure Pass missing in the course item

### ISSUE THREAD

**Issue by ZuberAgwan** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#37]
# Module: Lab 03: Expand your Teams Phone Environment to use Direct Routing
#### Step: 00

Description of issue
"Submit the Promo code and select Claim Promo Code" 
This step returns error and doesn't complete the Azure Pass redemption, resulting in students getting stuck on this step and not able to move forward without creating a new trial account 

Azure Subscription should be added in the lab tenant by the lab hosting provider or the step to redeem the pass code should be moved on the very beginning of the lab in the Lab 01: Configure the lab environment 

Also, the option to include Azure Pass is not present in the courseware marketplace for this item, Please add Azure passes with this course

**Comment by dahans-msft2** [comment]
We added some steps in PR #53 to get passed this issue.  In the future, we will be removing the Azure Pass and moving to CloudSlice instead.  The Azure Pass should currently be available in the courseware marketplace, but I will double check.
