### ISSUE TITLE
Incomplete steps

### ISSUE THREAD

**Issue by ZuberAgwan** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#38]
# Module: Lab 03: Expand your Teams Phone Environment to use Direct Routing
#### Step: 4

Description of issue
In this task you will assign the Emergency Location Identification number to a location existing in Microsoft Teams Admin center already. it doesnt allow to modify and add ELIN address after verifying the location address. This step should be moved or combined with the Emergency address task performed in the following lab
Lab 02: Configure your environment for Teams Phone
Exercise 3: Configure a basic network topology for dynamic emergency calling
Task 3 - Add an emergency address
Step Number 15

**Comment by dahans-msft2** [comment]
This should be resolved with PRs #58 and #59
