### ISSUE TITLE
Error in Lab 2, Task 2, Step 22 and 24

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#70]
# Module: 01
#### Step: 22 and 24

Description of issue
Wrong name (and probably also value) in step 22
In these steps the proporties of the network site "Bellevue" is configured - not the network site "Tacoma".

**Comment by dahans-msft2** [comment]
These steps were clarified in PR #40 and #41
