### ISSUE TITLE
Cannot validate applied licenses

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#71]
# Module: 1
#### Step: 4

Description of issue
When selecting the license type "Office 364 E5" you do not get a list of applied licensed users

Just discovered - one or two browser refresh solves the issue (both in Edge and Chrome)

Repro steps:

1.
1.
1.

**Comment by Williams-Nest** [comment]
This might be because of GoDeploy's way of applyinbg licenses.

In my own 365 tenant it is shown correctly - but many course providers are using GoDeploy - 
maybe the wording should be changed to something like; 
"In many cases you can select **Office 365 E5** to see who have the licenses applied."

**Comment by dahans-msft2** [comment]
Closing as no repro
