### ISSUE TITLE
Contoso loves Teams does not exist

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#72]
# Module: 1
##### Step: 4

Description of issue
There is no Team called "Contoso loves Teams" - only a "Contoso" Team.
And there is no "Add a Channel" either - only select an existing channel "General"

Repro steps:

1.
1.
1.

**Comment by dahans-msft2** [comment]
Fixed in PR #49
