### ISSUE TITLE
Cannot change a validated Emergency Address information - also not the ELIN

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#74]
# Module: 2
##### Step: 4

Description of issue
You can’t change the address information for this location because it’s already been validated. 
If you need to change the address, delete the location and create a new one.

Repro steps:

1.
1.
1.

**Comment by dahans-msft2** [comment]
This should be resolved with fixes in PRs #58 and #59
