### ISSUE TITLE
Script for creating a Teams Room account does not work

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#76]
# Module: 2
## Lab: 4
###Exercise: 2
##### Step: 34

Description of issue
The editing is done as written
The script fails - and the remedy in step 38 does not work either

Upload a tested script to github - eventually where only the custom lab number has to be changed

Repro steps:

1.
1.
1.

**Comment by dahans-msft2** [comment]
Fixed with new instructions in PR #81
