### ISSUE TITLE
MTR provisioning script not working

### ISSUE THREAD

**Issue by hbunkradt** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#77]
# Module: 02
#### Step: 07

Description of issue

The script SkypeRoomProvisoningScript.ps1.txt is no longer useful to create a MTR.
Would be easier to create the MTR through EXO and assign the license in M365 portal.

Repro steps:
1. Download the script
2. Try to run the script
3. Script failed

**Comment by dahans-msft2** [comment]
Fixed with new instructions from PR #81
