### ISSUE TITLE
bad web site announcement (both in Edge and in Chrome)

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#79]
Lab: 3
Exercise 1
Task: 4
Step: 2
Description of issue
In step 2 there is a bad web site announcement (both in Edge and in Chrome)
You will have to open and accept to proceed

Repro steps:

**Comment by dahans-msft2** [comment]
Fixed the insecure URL in PR #81
