### ISSUE TITLE
Commitment of changes to dial plan cannot be done until a number is put in external prefix

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#80]
# Module: 2
##### Step: 10

Description of issue
You will not be able to select Save until you have put a number in the “External dialing prefix” and removed it again.
This looks very much as an interface error.

Repro steps:

1.
1.
1.

**Comment by dahans-msft2** [comment]
I experienced this issue too, likely a UI error that will eventually be fixed, but I added a note to perform the steps so the dial plan can be saved.  PR #81
