### ISSUE TITLE
Script for skype room provisioning

### ISSUE THREAD

**Issue by mct370770** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#82]
# Module: 2
#### Step: 27 and 33

Description of issue
Step 27 should in my case be "Choose 2" to get the wanted ENTERPRISEPREMIUM
And after step 33 the script still fails (attached screenshot)

Repro steps:

1.
1.
1
![2022-04-27 15_44_05-Window](https://user-images.githubusercontent.com/50733331/165533900-b18149d1-e607-4684-9c48-fac66dc3394a.png)
.

**Comment by dahans-msft2** [comment]
I've updated the instructions in Lab 4 to no longer use the SkypeRoomProvisioning script, as it was out of date and not meant for Teams Rooms.  Instead, I've included instructions for creating and configuring the Exchange mailbox for the Teams Meeting Room, as well as configuring Azure AD, calendar settings, etc...Please let me know if you have any issues with the new instructions.  Thanks.
