### ISSUE TITLE
Lab 3 Excercise 1: 

### ISSUE THREAD

**Issue by hbunkradt** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#91]
# Module: 00
#### Step: Import 

Description of issue
Import of the TeamsSBCConfig.ini, import a wrong sign in account, the codec for Teams has the wrong paylod type and the NAT IP address is wrong.

1. Install the SBC through the Azure marketplace
2. Export the Ini file from the new SBC and modify the following configuration.
3. Open the c:\Scripts\Backup\TeamsSBCConfig.ini and the downloaded Ini file from the new SBC
4. Copy the account data [Webusers] [\Webusers] from the downloaded file to the TeamsSBCConfig.ini
5. Change the NAT IP address [NATTranslation] to the correct IP from azure SBC ressource group SBC
6. Change [Audiocoders] , Audiocoder 2 103 to 104 and save the TeamsSBCConfig.ini
7. Import  the saved TeamsSBCConfig.ini to the SBC
8. Restart SBC and login should be possible

**Comment by dahans-msft2** [comment]
I'll look into this, but the TeamsSBCConfig.ini is only supposed to be used as a last resort.  I'll re-export the INI next time I update the lab and republish to ALH's.
