### ISSUE TITLE
Task 2 Configure a call Queue to forward to Voicemail

### ISSUE THREAD

**Issue by hbunkradt** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#92]
# Module: 01
#### Step: 11

The Group All Company does not exist on Lab Tenant

Use the Teams Client as global admin an create on org wide team with name All Company or use the M365 Admin to create a M365 Group and add all User to this Group

**Comment by dahans-msft2** [comment]
I believe I've fixed this issue with the next PR I'm releasing.
