### ISSUE TITLE
Task 4 - Request your public certificate from DigiCert

### ISSUE THREAD

**Issue by hbunkradt** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#94]
# Module: 01
#### Step: 09

Certificate request works fine, but Digicert want to have an approvement, before the certificate is send to the MOD Administrator.

See Email from Digicert:

Thank you for contacting us.

<
I reviewed the status of order #268174480 and found it to be currently pending. Please note that its status is a result of the pending domain validation for the lab67169.o365ready.com order, as listed in the order. To see if we are able to complete the DCV, I was able to send the validation email to the following allowed email addresses:

[admin@o365ready.com](mailto:admin@o365ready.com)
[administrator@o365ready.com](mailto:administrator@o365ready.com)
[hostmaster@o365ready.com](mailto:hostmaster@o365ready.com) [jd4e94gd3nv@networksolutionsprivateregistration.com](mailto:jd4e94gd3nv@networksolutionsprivateregistration.com)
[postmaster@o365ready.com](mailto:postmaster@o365ready.com)
[webmaster@o365ready.com](mailto:webmaster@o365ready.com)

Please let us know if you prefer a different validation method than via email if this proves inconvenient, such as validation via DNS TXT modification.
>
Resolution was to request the TXT record and add this to the DNS on RRAS. This is to complicate for students I think.

**Comment by dahans-msft2** [comment]
I'll investigate this, but it's the first I'm seeing the issue and haven't heard of anyone else having this issue.

**Comment by hbunkradt** [comment]
ok, I will have a new training on Novenber and will see If I have the same problem again. All my 12 students had the problem to get the certificate from Digicert automatically without validation.

**Comment by dahans-msft2** [comment]
Tested certificate provisioning in Skillable lab today and received the certificate almost immediately from Digicert.  Unable to reproduce, if this continues to happen, please reach out and let me know what ALH you're using.
