### ISSUE TITLE
Explanation of table

### ISSUE THREAD

**Issue by mct370770** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#95]
# Module: 1
#### Instructor manual Page 55

Description of issue
In the instructor manual the table on page 55 has now been updated - no more two identical colomns - 
in the slide 37 the same error has not been corrected.

BUT: I can see no logical explanation as to what the table shows.
Could somebody help me out here?

Repro steps:

1.
1.
1.

**Comment by hbunkradt** [comment]
I changed the slide by myself
![image](https://user-images.githubusercontent.com/24456014/195017534-2dcceba4-5714-491f-b211-d9bf99f686fb.png)

**Comment by dahans-msft2** [comment]
The table is described in the speaker notes on that PowerPoint slide (slide 37 in Module 00 PowerPoint):

> The core purpose of this is not for them to note it down, but to understand that the capabilities are less than Teams IP Phones, but will provide a useful experience somewhat similar to the existing functionality offered to the user by a Skype for Business Server homed IP phone

The instructor manual that you're referring to on Page 55 is no longer being updated or used now that we're using Microsoft Learn for our course materials and not Skillpipe any longer.  Please see this page on Microsoft Learn for the same content:  https://learn.microsoft.com/en-us/training/modules/migrate-voice-services-from-skype-for-business-server-to-teams/6-migrate-ip-phones
